### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by aschneid42** [space-physics/lowtran#11]
@scivision 
I'm still having trouble getting this to install, but now with a new error message:
Any ideas?

$ pip install -e .
Obtaining file:///C:/Projects/lowtran-master
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: xarray in c:\anaconda3\lib\site-packages (from lowtran==2.4.1) (0.12.3)
Requirement already satisfied: python-dateutil in c:\anaconda3\lib\site-packages (from lowtran==2.4.1) (2.6.1)
Requirement already satisfied: numpy>=1.16 in c:\anaconda3\lib\site-packages (from lowtran==2.4.1) (1.17.0)
Requirement already satisfied: pandas>=0.19.2 in c:\anaconda3\lib\site-packages (from xarray->lowtran==2.4.1) (0.24.1)
Requirement already satisfied: six>=1.5 in c:\anaconda3\lib\site-packages (from python-dateutil->lowtran==2.4.1) (1.11.0)
Requirement already satisfied: pytz>=2011k in c:\anaconda3\lib\site-packages (from pandas>=0.19.2->xarray->lowtran==2.4.1) (2017.3)
Installing collected packages: lowtran
  Running setup.py develop for lowtran
    ERROR: Command errored out with exit status 1:
     command: 'c:\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Projects\\lowtran-master\\setup.py'"'"'; __file__='"'"'C:\\        Projects\\lowtran-master\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(c        ompile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Projects\lowtran-master\
    Complete output (67 lines):
    running develop
    running build_scripts
    copying and adjusting HorizontalTransmittance.py -> build\scripts.win-amd64-3.6
    copying and adjusting ThermalRadiance.py -> build\scripts.win-amd64-3.6
    copying and adjusting UserHorizontalTransmittance.py -> build\scripts.win-amd64-3.6
    copying and adjusting ScatterRadiance.py -> build\scripts.win-amd64-3.6
    copying and adjusting TransmittanceGround2Space.py -> build\scripts.win-amd64-3.6
    copying and adjusting Wavelength2LowtranWavenumber.py -> build\scripts.win-amd64-3.6
    copying and adjusting SolarIrradiance.py -> build\scripts.win-amd64-3.6
    copying and adjusting UserDataHorizontalRadiance.py -> build\scripts.win-amd64-3.6
    running egg_info
    running build_src
    build_src
    building extension "lowtran7" sources
    f2py options: ['--quiet']
      adding 'build\src.win-amd64-3.6\build\src.win-amd64-3.6\fortranobject.c' to sources.
      adding 'build\src.win-amd64-3.6\build\src.win-amd64-3.6' to include_dirs.
      adding 'build\src.win-amd64-3.6\lowtran7-f2pywrappers.f' to sources.
    build_src: building npy-pkg config files
    writing lowtran.egg-info\PKG-INFO
    writing dependency_links to lowtran.egg-info\dependency_links.txt
    writing entry points to lowtran.egg-info\entry_points.txt
    writing requirements to lowtran.egg-info\requires.txt
    writing top-level names to lowtran.egg-info\top_level.txt
    reading manifest file 'lowtran.egg-info\SOURCES.txt'
    writing manifest file 'lowtran.egg-info\SOURCES.txt'
    running build_ext
    Looking for python36.dll
    Building import library (arch=AMD64): "c:\anaconda3\libs\libpython36.a" (from c:\anaconda3\python36.dll)
    objdump.exe: c:\anaconda3\python36.dll: File format not recognized
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Projects\lowtran-master\setup.py", line 11, in <module>
        setup(ext_modules=ext)
      File "C:\Users\ad006850\AppData\Local\Temp\pip-build-env-p40yuiio\overlay\Lib\site-packages\numpy\distutils\core.py", line 171, in setup
        return old_setup(**new_attr)
      File "C:\Users\ad006850\AppData\Local\Temp\pip-build-env-p40yuiio\overlay\Lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\ad006850\AppData\Local\Temp\pip-build-env-p40yuiio\overlay\Lib\site-packages\setuptools\command\develop.py", line 38, in run
        self.install_for_development()
      File "C:\Users\ad006850\AppData\Local\Temp\pip-build-env-p40yuiio\overlay\Lib\site-packages\numpy\distutils\command\develop.py", line 17, in install_for_d        evelopment
        old_develop.install_for_development(self)
      File "C:\Users\ad006850\AppData\Local\Temp\pip-build-env-p40yuiio\overlay\Lib\site-packages\setuptools\command\develop.py", line 140, in install_for_devel        opment
        self.run_command('build_ext')
      File "c:\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\ad006850\AppData\Local\Temp\pip-build-env-p40yuiio\overlay\Lib\site-packages\numpy\distutils\command\build_ext.py", line 116, in run
        force=self.force)
      File "C:\Users\ad006850\AppData\Local\Temp\pip-build-env-p40yuiio\overlay\Lib\site-packages\numpy\distutils\ccompiler.py", line 765, in new_compiler
        compiler = klass(None, dry_run, force)
      File "C:\Users\ad006850\AppData\Local\Temp\pip-build-env-p40yuiio\overlay\Lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 103, in __init__
        build_import_library()
      File "C:\Users\ad006850\AppData\Local\Temp\pip-build-env-p40yuiio\overlay\Lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 415, in build_impor        t_library
        return _build_import_library_amd64()
      File "C:\Users\ad006850\AppData\Local\Temp\pip-build-env-p40yuiio\overlay\Lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 471, in _build_impo        rt_library_amd64
        generate_def(dll_file, def_file)
      File "C:\Users\ad006850\AppData\Local\Temp\pip-build-env-p40yuiio\overlay\Lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 301, in generate_de        f
        raise ValueError("Symbol table not found")
    ValueError: Symbol table not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Projects\\lowtran-master\\        setup.py'"'"'; __file__='"'"'C:\\Projects\\lowtran-master\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"        ', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by scivision** [comment]
We are thinking of making Lowtran use a command line interface with a standalone exectuable instead of as an f2py module. This was necessary to resolve difficult problems due to f2py limitations with other packages we work with. That will probably be the ultimate solution here.

**Comment by scivision** [comment]
this is now fixed
