### ISSUE TITLE
AttributeError: module 'lowtran7' has no attribute 'lwtrn7'

### ISSUE THREAD

**Issue by JohannesPseiner** [space-physics/lowtran#18]
Hello,

I am running your code in Pycharm (Python 3.9) and was able to successfully compile the fortran file via MinGW (64 bit Windows 10). Afterwards, PyCharm was able to find and install the package "lowtran" within the PyCharm environment.

However, the following error message occurs on all example programs (e.g., ScatterRadiance.py):

Traceback (most recent call last):
  File "C:\Users\Johannes.Pseiner\Documents\PycharmProjects\pythonProject\lowtran-master\lowtran-master\HorizontalTransmittance.py", line 30, in <module>
    TR = lowtran.horiztrans(c1).squeeze()
  File "C:\Users\Johannes.Pseiner\Documents\PycharmProjects\pythonProject\lowtran-master\lowtran-master\lowtran\__init__.py", line 222, in horiztrans
    return _golowtran(c1)
  File "C:\Users\Johannes.Pseiner\Documents\PycharmProjects\pythonProject\lowtran-master\lowtran-master\lowtran\__init__.py", line 106, in _golowtran
    Tx,V,Alam,trace,unif,suma,irrad,sumvv = lowtran7.lwtrn7(
AttributeError: module 'lowtran7' has no attribute 'lwtrn7'  

It seems, as the attribute lwtrn7 within the lowtran7 module is unknown. What seems to be the issue here?

Thank you very much in advance!

**Comment by scivision** [comment]
I am not sure, Windows support is a bit shaky by f2py. I would try Windows Subsystem for Linux.
